### ISSUE TITLE
Multi GPU with Docker api:2.0cuda11.1

### ISSUE THREAD

**Issue by phamvietloi** [UKPLab/EasyNMT#50]
I am using Ubuntu 20.04 with 3 GPUs of RTX 2080. This is my docker-compose:
```
version: '2.3'

services: 
  easynmt:
    image: easynmt/api:2.0-cuda11.1
    restart: always
    runtime: nvidia
    volumes: 
      - ./cache:/cache
    ports: 
      - "24080:80"
    env_file: 
      - ./envfile

```
The envfile:
`EASYNMT_MODEL=m2m_100_1.2B
`

The first problem is that the service always use only the first GPU in my machine.
The second, one backend worker will take around 7GB of GPU's VRAM, so after a few requests of translate CUDA run out of memory and the code do not work any more (I think the spawned woker need another 7GB VRAM of GPU).

I have my own solution for both: set MAX_WORKERS_BACKEND=1.
start 3 services of easynmt with specificed GPU then use nginx as load balancer to group of 3 easynmt services.

Did I do something wrong? or Any better solution in this case?
